services:

  postgres:
    ports:
      - "5432:5432"

  kafka:
    ports:
      - "9092:9092"
      - "9093:9093"

  playwallet:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app


