FROM golang:1.24-alpine

WORKDIR /app
RUN go install github.com/air-verse/air@latest
ENV TZ=Asia/Singapore
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY go.mod go.mod
COPY go.sum go.sum
COPY . .


WORKDIR /app

# comment if have module replacement, otherwise uncomment
# RUN go mod download 

ENTRYPOINT ["air"]



