env: prod
loglv: -4 # debug for slog
kafka:
  addr: walletkafka:9092
  consumer_group: walletsvc
  topics:
    - senderconfirm: sendconfirm
    - receiverconfirm: recvconfirm
    - cancel: cancel
pg:
  addr: walletpg
  pwd: password
  user: admin
  db: playwallet
  port: 5432
http:
  addr: ":1323"
