# for e2e test usage
env: test
loglv: -4 # debug for slog
kafka:
  addr: localhost:9093
  topics:
    - senderconfirm: testsendconfirm
    - receiverconfirm: testrecvconfirm
    - cancel: testcancel
pg:
  addr: localhost
  pwd: password
  user: admin
  db: postgres # this is the default db, for testing, would connect to this db first then create tmp db instead, 
  port: 5432
http:
  addr: ":0" # random port
